### PR TITLE
bump app-mobilephone/scrcpy (1.9)

### PR DESCRIPTION
**Pull request by hrk**

### CODE REVIEW

**Comment by hrk** [comment]
I just noticed that 1.9 won't produce a working binary due to two upstream issues:
1: portable flag defaults to true (fixed upstream)
2: when portable flag is manually set to false in the ebuild, compile process fails due to a bad preprocessor rule.

Temporary workaround: build w/ portable=true and then launch with
> export SCRCPY_SERVER_PATH=/usr/share/scrcpy/scrcpy-server.jar

**Comment by maggu2810** [comment]
Well, did I get you right: If we merge this PR there are two issues:
* v1.9 does not build (I assume the fix is applied upstream after 1.9 has been released)
* we need a workaround to start the tool

If that's tree, I assume it is better to wait for a working version.

**Comment by hrk** [comment]
Ok, spoke with the developer and there are already two upstream patches that fix the issues for 1.9. I have added the commits as .patch files and amended the ebuild.

Let me know if you think I did it the right way. :)

**Comment by hrk** [comment]
Question: I didn't commit/push the updated Manifest file, is it required or is it automatically taken care of when publishing the repo to gentoo-mirror?

**Comment by maggu2810** [comment]
I marked the overlay not to use manifests anymore: https://github.com/maggu2810/maggu2810-overlay/commit/d83c4227f43f6de2a06c694c4775d978e2215e00
This makes it easier for PRs.
As this is an unofficial repo, it should not matter.

What do you mean by "when publishing the repo to gentoo-mirror"?

**Comment by hrk** [comment]
I'm still new at this "custom ebuild overlay"-stuff, I did:
> eselect repository
> eselect repository enable  maggu2810-overlay
> emerge scrcpy

If I check the contents of /var/db/repos/maggu2810-overlay/.git/config I see
> url = https://github.com/gentoo-mirror/maggu2810-overlay.git

That's why I wrote about gentoo-mirror.

When I forked the repo, out of habit I issued a 'repoman manifest' every time I modified the ebuild so that I could test it. I think I understand now that it wasn't necessary, right?

**Comment by maggu2810** [comment]
Sorry, I don't know myself how this "gentoo-mirror" is working.
My repository is hosted (from my side) here: https://github.com/maggu2810/maggu2810-overlay
The mirror is there: https://github.com/gentoo-mirror/maggu2810-overlay

Will try to have a look at but perhaps this is created for all overlays that are part of the Layman list.

Repoman itself also identifies other stuff, manifest is just one point.
From now you don't need to generate a manifest anymore for this overlay.

**Comment by hrk** [comment]
Unfortunately it appears that the mirror has a Manifest file that this repo hasn't (https://github.com/gentoo-mirror/maggu2810-overlay/tree/master/app-mobilephone/scrcpy) and emerge fails claiming that the new ebuild is missing in the manifest.
Manually issuing a repoman manifest got it working, but I don't think it's the long term solution. Unfortunately, I don't know anything about this and can't be of help.

**Comment by maggu2810** [comment]
As written before, I don't know at which time intervals gentoo-mirror sync the repository.
You could switch (or add) the other remote (mine official one) to be sure to use the latest sources.
Do you know how to add remotes (Git workflow)?

**Comment by hrk** [comment]
Sorry I wasn't clear: when I checked, the gentoo-mirror already had the 1.9 ebuild file, so (somehow) the mirror happened very soon, but the Manifest file (which is present in gentoo-mirror but not in your repo) did not contain the 1.9 ebuild hash (wasn't updated). I see you're doing some tests. Good luck! Let me know if I can help.

**Comment by maggu2810** [comment]
Here you can see at which time the mirror has been updated:
https://github.com/gentoo-mirror/maggu2810-overlay/commits/master

Here are the commits in my repository
https://github.com/maggu2810/maggu2810-overlay/commits/master

The commits
* do not use manifests
* remove existing manifests

are missing.

So you are right, the ebuild you provided is part of gentoo-mirror but the manifest (that still exists) does not contain the entry for the 1.9 ebuild.

So, let's wait for a new sync of the mirror (whenever it happen).

For the time being, don't use the mirror. :wink:

**Pull request merged**
